// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lobbies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (creator_id, name, country, city, address, event_time, chat_link, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
`

type CreateLobbyParams struct {
	CreatorID  int64              `json:"creator_id"`
	Name       string             `json:"name"`
	Country    string             `json:"country"`
	City       string             `json:"city"`
	Address    *string            `json:"address"`
	EventTime  pgtype.Timestamptz `json:"event_time"`
	ChatLink   *string            `json:"chat_link"`
	Visibility LobbyVisibility    `json:"visibility"`
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, createLobby,
		arg.CreatorID,
		arg.Name,
		arg.Country,
		arg.City,
		arg.Address,
		arg.EventTime,
		arg.ChatLink,
		arg.Visibility,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.EventTime,
		&i.ChatLink,
		&i.Visibility,
		&i.CreatedAt,
		&i.Country,
		&i.City,
		&i.Address,
	)
	return i, err
}

const deleteLobby = `-- name: DeleteLobby :exec
DELETE
FROM lobbies
WHERE id = $1
  AND creator_id = $2
`

type DeleteLobbyParams struct {
	ID        int64 `json:"id"`
	CreatorID int64 `json:"creator_id"`
}

// Members cascade-delete via the lobby_members foreign key.
func (q *Queries) DeleteLobby(ctx context.Context, arg DeleteLobbyParams) error {
	_, err := q.db.Exec(ctx, deleteLobby, arg.ID, arg.CreatorID)
	return err
}

const getLobby = `-- name: GetLobby :one
SELECT id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
FROM lobbies
WHERE id = $1
`

func (q *Queries) GetLobby(ctx context.Context, id int64) (Lobby, error) {
	row := q.db.QueryRow(ctx, getLobby, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.EventTime,
		&i.ChatLink,
		&i.Visibility,
		&i.CreatedAt,
		&i.Country,
		&i.City,
		&i.Address,
	)
	return i, err
}

const listLobbiesByCreator = `-- name: ListLobbiesByCreator :many
SELECT id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
FROM lobbies
WHERE creator_id = $1
ORDER BY event_time ASC
`

func (q *Queries) ListLobbiesByCreator(ctx context.Context, creatorID int64) ([]Lobby, error) {
	rows, err := q.db.Query(ctx, listLobbiesByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lobby{}
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.EventTime,
			&i.ChatLink,
			&i.Visibility,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLobbiesFiltered = `-- name: ListLobbiesFiltered :many
SELECT id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
FROM lobbies
WHERE event_time > now()
  AND ($1::text = '' OR lower(city) = lower($1::text))
  AND ($2::timestamptz IS NULL OR event_time <= $2::timestamptz)
ORDER BY event_time ASC
LIMIT $4 OFFSET $3
`

type ListLobbiesFilteredParams struct {
	City  string             `json:"city"`
	Until pgtype.Timestamptz `json:"until"`
	Off   int32              `json:"off"`
	Lim   int32              `json:"lim"`
}

// Upcoming lobbies, optionally narrowed to a city (case-insensitive) and to a
// time window (events at or before @until), soonest first, paginated. Pass an
// empty city to skip the city filter and a NULL until to skip the time filter.
func (q *Queries) ListLobbiesFiltered(ctx context.Context, arg ListLobbiesFilteredParams) ([]Lobby, error) {
	rows, err := q.db.Query(ctx, listLobbiesFiltered,
		arg.City,
		arg.Until,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lobby{}
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.EventTime,
			&i.ChatLink,
			&i.Visibility,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyLobbies = `-- name: ListMyLobbies :many
SELECT id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
FROM lobbies l
WHERE l.creator_id = $1
   OR l.id IN (SELECT lobby_id
               FROM lobby_members
               WHERE user_id = $1
                 AND status = 'approved')
ORDER BY l.event_time ASC
`

// Every lobby the user takes part in: ones they created, plus ones they were
// approved to join.
func (q *Queries) ListMyLobbies(ctx context.Context, creatorID int64) ([]Lobby, error) {
	rows, err := q.db.Query(ctx, listMyLobbies, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lobby{}
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.EventTime,
			&i.ChatLink,
			&i.Visibility,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLobby = `-- name: UpdateLobby :one
UPDATE lobbies
SET name       = $2,
    country    = $3,
    city       = $4,
    address    = $5,
    event_time = $6,
    chat_link  = $7,
    visibility = $8
WHERE id = $1
  AND creator_id = $9
RETURNING id, creator_id, name, event_time, chat_link, visibility, created_at, country, city, address
`

type UpdateLobbyParams struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Country    string             `json:"country"`
	City       string             `json:"city"`
	Address    *string            `json:"address"`
	EventTime  pgtype.Timestamptz `json:"event_time"`
	ChatLink   *string            `json:"chat_link"`
	Visibility LobbyVisibility    `json:"visibility"`
	CreatorID  int64              `json:"creator_id"`
}

func (q *Queries) UpdateLobby(ctx context.Context, arg UpdateLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, updateLobby,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.City,
		arg.Address,
		arg.EventTime,
		arg.ChatLink,
		arg.Visibility,
		arg.CreatorID,
	)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.EventTime,
		&i.ChatLink,
		&i.Visibility,
		&i.CreatedAt,
		&i.Country,
		&i.City,
		&i.Address,
	)
	return i, err
}
