// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"
)

const addMember = `-- name: AddMember :one
INSERT INTO lobby_members (lobby_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (lobby_id, user_id) DO UPDATE
    SET status = EXCLUDED.status
RETURNING lobby_id, user_id, status, joined_at
`

type AddMemberParams struct {
	LobbyID int64            `json:"lobby_id"`
	UserID  int64            `json:"user_id"`
	Status  MembershipStatus `json:"status"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (LobbyMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.LobbyID, arg.UserID, arg.Status)
	var i LobbyMember
	err := row.Scan(
		&i.LobbyID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const countApprovedMembers = `-- name: CountApprovedMembers :one
SELECT count(*)
FROM lobby_members
WHERE lobby_id = $1
  AND status = 'approved'
`

func (q *Queries) CountApprovedMembers(ctx context.Context, lobbyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedMembers, lobbyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMember = `-- name: GetMember :one
SELECT lobby_id, user_id, status, joined_at
FROM lobby_members
WHERE lobby_id = $1
  AND user_id = $2
`

type GetMemberParams struct {
	LobbyID int64 `json:"lobby_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (LobbyMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.LobbyID, arg.UserID)
	var i LobbyMember
	err := row.Scan(
		&i.LobbyID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const listApprovedMembers = `-- name: ListApprovedMembers :many
SELECT lobby_id, user_id, status, joined_at
FROM lobby_members
WHERE lobby_id = $1
  AND status = 'approved'
ORDER BY joined_at ASC
`

func (q *Queries) ListApprovedMembers(ctx context.Context, lobbyID int64) ([]LobbyMember, error) {
	rows, err := q.db.Query(ctx, listApprovedMembers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LobbyMember{}
	for rows.Next() {
		var i LobbyMember
		if err := rows.Scan(
			&i.LobbyID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembers = `-- name: ListPendingMembers :many
SELECT lobby_id, user_id, status, joined_at
FROM lobby_members
WHERE lobby_id = $1
  AND status = 'pending'
ORDER BY joined_at ASC
`

func (q *Queries) ListPendingMembers(ctx context.Context, lobbyID int64) ([]LobbyMember, error) {
	rows, err := q.db.Query(ctx, listPendingMembers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LobbyMember{}
	for rows.Next() {
		var i LobbyMember
		if err := rows.Scan(
			&i.LobbyID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE
FROM lobby_members
WHERE lobby_id = $1
  AND user_id = $2
`

type RemoveMemberParams struct {
	LobbyID int64 `json:"lobby_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.LobbyID, arg.UserID)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE lobby_members
SET status = $3
WHERE lobby_id = $1
  AND user_id = $2
RETURNING lobby_id, user_id, status, joined_at
`

type UpdateMemberStatusParams struct {
	LobbyID int64            `json:"lobby_id"`
	UserID  int64            `json:"user_id"`
	Status  MembershipStatus `json:"status"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (LobbyMember, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.LobbyID, arg.UserID, arg.Status)
	var i LobbyMember
	err := row.Scan(
		&i.LobbyID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
