// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LobbyVisibility string

const (
	LobbyVisibilityPublic  LobbyVisibility = "public"
	LobbyVisibilityPrivate LobbyVisibility = "private"
)

func (e *LobbyVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LobbyVisibility(s)
	case string:
		*e = LobbyVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for LobbyVisibility: %T", src)
	}
	return nil
}

type NullLobbyVisibility struct {
	LobbyVisibility LobbyVisibility `json:"lobby_visibility"`
	Valid           bool            `json:"valid"` // Valid is true if LobbyVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLobbyVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.LobbyVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LobbyVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLobbyVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LobbyVisibility), nil
}

type MembershipStatus string

const (
	MembershipStatusPending  MembershipStatus = "pending"
	MembershipStatusApproved MembershipStatus = "approved"
	MembershipStatusRejected MembershipStatus = "rejected"
	MembershipStatusBanned   MembershipStatus = "banned"
)

func (e *MembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipStatus(s)
	case string:
		*e = MembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipStatus: %T", src)
	}
	return nil
}

type NullMembershipStatus struct {
	MembershipStatus MembershipStatus `json:"membership_status"`
	Valid            bool             `json:"valid"` // Valid is true if MembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipStatus), nil
}

type Lobby struct {
	ID          int64              `json:"id"`
	CreatorID   int64              `json:"creator_id"`
	Name        string             `json:"name"`
	EventTime   pgtype.Timestamptz `json:"event_time"`
	ChatLink    *string            `json:"chat_link"`
	Visibility  LobbyVisibility    `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Country     string             `json:"country"`
	City        string             `json:"city"`
	Address     *string            `json:"address"`
	Description *string            `json:"description"`
}

type LobbyMember struct {
	LobbyID  int64              `json:"lobby_id"`
	UserID   int64              `json:"user_id"`
	Status   MembershipStatus   `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID         int64              `json:"id"`
	Username   *string            `json:"username"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Locale     string             `json:"locale"`
	Timezone   string             `json:"timezone"`
	City       string             `json:"city"`
	TimeFilter string             `json:"time_filter"`
}
