// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) (LobbyMember, error)
	CountApprovedMembers(ctx context.Context, lobbyID int64) (int64, error)
	CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error)
	// Members cascade-delete via the lobby_members foreign key.
	DeleteLobby(ctx context.Context, arg DeleteLobbyParams) error
	GetLobby(ctx context.Context, id int64) (Lobby, error)
	GetMember(ctx context.Context, arg GetMemberParams) (LobbyMember, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListApprovedMembers(ctx context.Context, lobbyID int64) ([]LobbyMember, error)
	ListLobbiesByCreator(ctx context.Context, creatorID int64) ([]Lobby, error)
	// Upcoming lobbies, optionally narrowed to a city (case-insensitive) and to a
	// time window (events at or before @until), soonest first, paginated. Pass an
	// empty city to skip the city filter and a NULL until to skip the time filter.
	ListLobbiesFiltered(ctx context.Context, arg ListLobbiesFilteredParams) ([]Lobby, error)
	// Every lobby the user takes part in: ones they created, plus ones they were
	// approved to join.
	ListMyLobbies(ctx context.Context, creatorID int64) ([]Lobby, error)
	ListPendingMembers(ctx context.Context, lobbyID int64) ([]LobbyMember, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	SetUserCity(ctx context.Context, arg SetUserCityParams) error
	SetUserLocale(ctx context.Context, arg SetUserLocaleParams) error
	SetUserTimeFilter(ctx context.Context, arg SetUserTimeFilterParams) error
	SetUserTimezone(ctx context.Context, arg SetUserTimezoneParams) error
	UpdateLobby(ctx context.Context, arg UpdateLobbyParams) (Lobby, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (LobbyMember, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
