// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, created_at, locale, timezone, city, time_filter
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Locale,
		&i.Timezone,
		&i.City,
		&i.TimeFilter,
	)
	return i, err
}

const setUserCity = `-- name: SetUserCity :exec
UPDATE users
SET city = $2
WHERE id = $1
`

type SetUserCityParams struct {
	ID   int64  `json:"id"`
	City string `json:"city"`
}

func (q *Queries) SetUserCity(ctx context.Context, arg SetUserCityParams) error {
	_, err := q.db.Exec(ctx, setUserCity, arg.ID, arg.City)
	return err
}

const setUserLocale = `-- name: SetUserLocale :exec
UPDATE users
SET locale = $2
WHERE id = $1
`

type SetUserLocaleParams struct {
	ID     int64  `json:"id"`
	Locale string `json:"locale"`
}

func (q *Queries) SetUserLocale(ctx context.Context, arg SetUserLocaleParams) error {
	_, err := q.db.Exec(ctx, setUserLocale, arg.ID, arg.Locale)
	return err
}

const setUserTimeFilter = `-- name: SetUserTimeFilter :exec
UPDATE users
SET time_filter = $2
WHERE id = $1
`

type SetUserTimeFilterParams struct {
	ID         int64  `json:"id"`
	TimeFilter string `json:"time_filter"`
}

func (q *Queries) SetUserTimeFilter(ctx context.Context, arg SetUserTimeFilterParams) error {
	_, err := q.db.Exec(ctx, setUserTimeFilter, arg.ID, arg.TimeFilter)
	return err
}

const setUserTimezone = `-- name: SetUserTimezone :exec
UPDATE users
SET timezone = $2
WHERE id = $1
`

type SetUserTimezoneParams struct {
	ID       int64  `json:"id"`
	Timezone string `json:"timezone"`
}

func (q *Queries) SetUserTimezone(ctx context.Context, arg SetUserTimezoneParams) error {
	_, err := q.db.Exec(ctx, setUserTimezone, arg.ID, arg.Timezone)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, first_name, last_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET username   = EXCLUDED.username,
        first_name = EXCLUDED.first_name,
        last_name  = EXCLUDED.last_name
RETURNING id, username, first_name, last_name, created_at, locale, timezone, city, time_filter
`

type UpsertUserParams struct {
	ID        int64   `json:"id"`
	Username  *string `json:"username"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Locale,
		&i.Timezone,
		&i.City,
		&i.TimeFilter,
	)
	return i, err
}
